version: '3.11.4'

services:
  python:
    image: mlassignment2:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .dockerFile
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
  mlflow:
    command: mlflow server -h 0.0.0.0 --gunicorn-opts "--timeout 300"
    # command: tail -f /dev/null
    image: mlflow:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 8000:8080